CarRepair.MVC/Controllers/AppointmentsController.cs
using CarRepair.MVC.Data;
using CarRepair.MVC.Interfaces;
using CarRepair.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace CarRepair.MVC.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly ILogger<AppointmentsController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMemoryCache _memoryCache;
        private readonly IAppointmentRepository _appointmentRepo;

        public AppointmentsController(
                            ILogger<AppointmentsController> logger, 
                            UserManager<IdentityUser> userManager, 
                            IMemoryCache memoryCache, 
                            IAppointmentRepository appointmentRepo)
        {
            _logger = logger;
            _userManager = userManager;
            _memoryCache = memoryCache;
            _appointmentRepo = appointmentRepo;
        }

        public async Task<IActionResult> Index(int page = 1, int pageSize = 9, AppointmentStatus appointmentStatus = AppointmentStatus.NotSeen)
        {
            var curUserId = _userManager.GetUserId(User);
            string dataCacheKey = $"Appointments_{appointmentStatus}_{page}_{pageSize}";
            
            var repairs = await  _appointmentRepo.GetAllAsync(
                    userId: curUserId!, 
                    dataCacheKey: dataCacheKey, 
                    page: page, 
                    pageSize: pageSize,
                    appointmentStatus
                    );
            
            var pageCount = await _appointmentRepo.GetAllItemsCountAsync(curUserId!, appointmentStatus);

            var pager = new Pager(pageCount, page, pageSize);
            ViewBag.pager = pager;

            return View(repairs);
        }

        [HttpGet]
        public IActionResult Send()
        {
            
            var repair = new Repair() ;
            return View(repair);
        }
        [HttpPost]
        public IActionResult Send(Repair repair)
        {
            var newRepair = repair;
            _appointmentRepo.Add(newRepair);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Accept([FromForm]int id)
        {
            var appointment = await _appointmentRepo.GetByIdAsync(id);

            appointment.AppointmentStatus = AppointmentStatus.Accept;

            await _appointmentRepo.Update(appointment);

            // TODO: Handle redirection
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int repairId)
        {
            var repair = await _appointmentRepo.GetByIdAsync(repairId);

            _appointmentRepo.Delete(repair);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CarRepair.MVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vehicle Service Management System</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    @* <link rel="stylesheet" href="~/CarRepair.MVC.styles.css" asp-append-version="true" /> *@
    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" /> *@
    @* <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Feather Icons -->
    <link href="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.css" rel="stylesheet">

    <style>
        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100;
            padding: 48px 0 0;
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        .nav-link span {
            margin-right: 10px;
        }

        .content {
            margin-left: 200px;
            padding: 20px;
        }
    </style>
</head>

<body>
    <!-- Sidebar -->
    <nav class="bg-dark sidebar">
        <div class="sidebar-sticky">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" 
                        asp-area=""
                        asp-controller="Admin"
                        asp-action="Dashboard"
                    >
                        <span data-feather="home"></span>
                        Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        asp-area=""
                        asp-controller="Mechanic"
                        asp-action="Index"
                    >
                        <span data-feather="user"></span>
                        Mechanic List
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" 
                        asp-area=""
                        asp-controller="Admin"
                        asp-action="ServiceRequests"
                    >
                        <span data-feather="activity"></span>
                        Service Requests
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="bar-chart-2"></span>
                        Report
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="list"></span>
                        Category List
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="layers"></span>
                        Service List
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" 
                        asp-area=""
                        asp-controller="Admin"
                        asp-action="UserList"
                    >
                        <span data-feather="users"></span>
                        User List
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="settings"></span>
                        Settings
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content">
        @RenderBody()
    </div>


    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace(); // Replace feather icons
    </script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

CarRepair.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRepair.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarRepair.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5">
        <a asp-area="" asp-page="/Index" class="navbar-brand d-flex align-items-center">
            <h1 class="m-0" style="color: red;">
                @* <img class="img-fluid me-3" src="img/icon/icon-02-primary.png" alt=""> *@
                Car Repair System
            </h1>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav mx-auto bg-light pe-4 py-3 py-lg-0">
                <a class="nav-item nav-link active">Home</a>
                <a href="#about" class="nav-item nav-link">About Us</a>
                <a href="#service" class="nav-item nav-link">Our Services</a>
                <a asp-area="" asp-controller="Admin" asp-action="Dashboard" class="nav-item nav-link">Admin</a>
                @* <a href="contact.html" class="nav-item nav-link">Contact Us</a> *@
            </div>
            <div class="h-100 d-lg-inline-flex align-items-center d-none">
                <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i class="fab fa-twitter"></i></a>
                <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-square rounded-circle bg-light text-primary me-0" href=""><i class="fab fa-instagram"></i></a>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    </header>


    @RenderBody()


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarRepair.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarRepair.MVC/Views/Shared/_PagerPartial.cshtml
@model Pager

<div class="container">
    @if(@Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if(@Model.CurrentPage >1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Appointments" asp-action="Index" asp-route-page="@Model.StartPage">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Appointments" asp-action="Index" asp-route-page="@(Model.CurrentPage-1)"> Prev </a>
                </li> 
            }

            @for(var pge = @Model.StartPage; pge <= @Model.EndPage; pge++)
            {
                <li class="page-item @(pge == @Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Appointments" asp-action="Index" asp-route-page="@pge">@pge</a>

                </li>
            }

            @if(@Model.CurrentPage < @Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Appointments" asp-action="Index" asp-route-page="@(Model.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Appointments" asp-action="Index" asp-route-page="@Model.TotalPages">Last</a>
                </li>
            }
            

        </ul>
    }

</div>

CarRepair.MVC/Views/Shared/_PagerPartialNew.cshtml
@model PagerVM

<div class="container">
    @if(@Model.Pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if(@Model.Pager.CurrentPage >1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@Model.Pager.StartPage">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@(Model.Pager.CurrentPage-1)"> Prev </a>
                </li> 
            }

            @for(var pge = @Model.Pager.StartPage; pge <= @Model.Pager.EndPage; pge++)
            {
                <li class="page-item @(pge == @Model.Pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@pge">@pge</a>

                </li>
            }

            @if(@Model.Pager.CurrentPage < @Model.Pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@(Model.Pager.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@Model.Pager.TotalPages">Last</a>
                </li>
            }
            

        </ul>
    }

</div>